### ISSUE TITLE
Тест проверки headers

### ISSUE THREAD

**Issue by v1-wizard** [Yurasb/api_test_automation#2]
Создать тест, который проверит наличие всех ожидаемых http заголовков. Проверить их соответсвие ожидаемым.

**Comment by Yurasb** [comment]
Ожидаемые значения как хранить? Не совсем догоняю.

**Comment by Yurasb** [comment]
Тест есть, но он фейлится из-за изменяющихся значений типа айдишника, времени и т.п. Как это хэндлить?

**Comment by Yurasb** [comment]
Разделил тест по полям хэдера. Те что меняются (дата, айдишник и тп) - проверяю на наличие, а не на оинаковые значения.
